# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/ for more options

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/codeforgood-org/golang-book-api

issues:
  exclude-use-default: false
  max-same-issues: 0
